version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: PostShare
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    networks:
      - app-network

  java-app:
    build: .
    container_name: java-app
    depends_on:
      - mysql
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/PostShare?allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=rootpassword
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


volumes:
  mysql-data:
